name: publish

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_CD }}

      - name: Build image
        run: |
          docker build . --tag ghcr.io/carlosmaroto-daweb/safari:latest
          docker push ghcr.io/carlosmaroto-daweb/safari:latest
  
  deploy:
    needs: create-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Server
        run: |
          echo "${{ secrets.AUTH_PASS }}" > mi_clave.pem
          chmod 600 mi_clave.pem
          ssh -i mi_clave.pem -o StrictHostKeyChecking=no ${{ secrets.AUTH_SERVER }} << EOF
            mkdir ejemplo2