name: publish

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DOCKER_IMAGE: safari:latest
  DOCKER_CONTAINER: web_safari
  PORT: 8000
  NGINX_LOCATION: /safari/

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_CD }}

      - name: Build image
        run: |
          docker build . --tag ghcr.io/carlosmaroto-daweb/$DOCKER_IMAGE
          docker push ghcr.io/carlosmaroto-daweb/$DOCKER_IMAGE
  
  deploy:
    needs: create-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Server
        run: |
          echo "${{ secrets.AUTH_PASS }}" > mi_clave.pem
          chmod 600 mi_clave.pem
          ssh -i mi_clave.pem -o StrictHostKeyChecking=no ${{ secrets.AUTH_SERVER }} << EOF
            sudo docker login ghcr.io -u carlosmaroto-daweb -p ${{ secrets.TOKEN_CD }}
            sudo docker pull ghcr.io/carlosmaroto-daweb/$DOCKER_IMAGE
            sudo docker stop $DOCKER_CONTAINER && sudo docker rm $DOCKER_CONTAINER
            sudo docker run -d \
              --name $DOCKER_CONTAINER \
              -p $PORT:80 \
              --restart always \
              ghcr.io/carlosmaroto-daweb/$DOCKER_IMAGE

            if sudo grep -q "location $NGINX_LOCATION" /etc/nginx/sites-available/default; then
              if sudo grep -q "proxy_pass http://localhost:$PORT;" /etc/nginx/sites-available/default | grep "$NGINX_LOCATION"; then
                echo "Port already configured correctly"
              else
                sudo sed -i "/location $NGINX_LOCATION/,/}/ s|proxy_pass http://localhost:[0-9]*;|proxy_pass http://localhost:$PORT;|g" /etc/nginx/sites-available/default
                echo "Port updated in nginx configuration"
                sudo systemctl reload nginx
              fi 
            else
              echo "Adding location $NGINX_LOCATION to nginx configuration"
              sudo bash -c 'cat << EOF >> /etc/nginx/sites-available/default

              location $NGINX_LOCATION {
                rewrite ^$NGINX_LOCATION(.*)$ /\$1 break;
                proxy_pass http://localhost:$PORT;
                proxy_set_header Host \$host;
                proxy_set_header X-Real-IP \$remote_addr;
                proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto \$scheme;
              }
              EOF'
              sudo systemctl reload nginx
            fi
          EOF